name: Move assigned issues into In-Progess

on:
  issues:
    types: [assigned]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: Fmanuel809/github-project-automation-v2@master
        with:
          project: Test
          column: In Progress
          repo-token: ${{ secrets.TEST_PROJECT_TOKEN }}
